### PR TITLE
Code for Module 5 UW JS -- More Fun Than The Law Allows...

### PR DESCRIPTION
**Pull request by jjs0sbw**
Again not tested as well as I would like but we may get to some discussion of automatic testing?

### CODE REVIEW

**Comment by jjs0sbw** [comment]
OK.. Just checked a cloned copy and I have some issues..

So.. I will fix the errors and push an update..

**Comment by jjs0sbw** [comment]
OK.. quick set of test.. need automated test coverage..

These are getting to big to do by hand..

Works much better..

**Comment by jamdon** [comment]
Your package.json is missing one of your dependencies, preventing your server from running.

**Comment by jjs0sbw** [comment]
@jamdon I just downloaded and tested the file locally, which worked.

My package.json file is:
"name": "module_5_jjs",
  "version": "0.1.0",
  "description": "UW JS Module 5 HQ",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Joseph Simpson jjs0sbw@gmail.com (http://systemsconcept.org)",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.1",
    "express": "^4.13.4"
  }
}

Therefore, the server works on my end...  and 
I can not find anything to fix?

Any more hints as to what I might be doing wrong?

My server runs locally and the program works..

Any further tips or comments would be very helpful as I can not find anything to fix???

I t might be that I am depending on some local globally installed file, but I have no idea about hoe to find out..

**Comment by jjs0sbw** [comment]
OK... quick test of a local download shows it works on my machine..

Thanks for your help..

**Comment by jamdon** [comment]
Works good. 👍

**Comment by jjs0sbw** [comment]
I am still trying to figure out why it worked without lodash...

I got a message about lodash being redundant when I tried to install it..

So, maybe it is or was loaded some other way..

Take care..

On Fri, May 20, 2016 at 11:38 PM, jamdon notifications@github.com wrote:

> Works good. 👍
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/JSCRIPT300-Spring2016/Module_5/pull/12#issuecomment-220762106

## 

Joe Simpson
“Reasonable people adapt themselves to the world. Unreasonable people
attempt to adapt the world to themselves. All progress, therefore, depends
on unreasonable people.”
George Bernard Shaw

**Pull request closed without merging**
